version: "3.9"
services:
  postgres:
    image: postgres:13
    restart: always
    ports:
      - "5433:5433"
    container_name: "potdb"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pot
  server:
    build: .
    container_name: "pot"
    ports:
      - "8081:8081"
    depends_on:
      - postgres
