kumuluzee:
  name: pot-service
  version: 1.0.0
  env:
    name: dev
  server:
    base-url: http://localhost:8081
    http:
      port: 8081

  datasources:
    - jndi-name: jdbc/potDS
      connection-url: jdbc:postgresql://localhost:5433/pot
      username: postgres
      password: postgres
      max-pool-size: 20

  config:
    consul:
      agent: http://consul:8500
  discovery:
    cluster: 1
    consul:
      agent: http://consul:8500
    ttl: 20
    ping-interval: 15

  health:
    checks:
      data-source-health-check:
        jndi-name: jdbc/potDS
        type: liveness
      http-health-check:
        - connection-url: http://localhost:8081/v1/pot


  metrics:
    web-instrumentation:
      - name: pot-endpoint
        url-pattern: /v1/pot/*
    servlet:
      enabled: true
      mapping: /metrics

  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                    <Configuration name="customers">
                        <Appenders>
                            <Console name="console" target="SYSTEM_OUT">
                                <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                            </Console>
                        </Appenders>
                        <Loggers>
                            <!-- Resources (REST) -->
                            <Logger name="com.kumuluz.ee.samples.kumuluzee_logs.CustomerResource" level="trace" additivity="false">
                                <AppenderRef ref="console"/>
                            </Logger>
                    
                            <!-- Default logger -->
                            <Root level="info">
                                <AppenderRef ref="console"/>
                            </Root>
                        </Loggers>
                    </Configuration>'

  external-api:
    mapquestApi: https://www.mapquestapi.com/directions/v2/optimizedroute?key=C0a6ATPbuQ30XjwFnoy7xAYYmajidgtD