kumuluzee:
  name: pot-service
  version: 1.0.0
  env:
    name: dev
  server:
    base-url: http://localhost:8081
    http:
      port: 8081

  datasources:
    - jndi-name: jdbc/potDS
      connection-url: jdbc:postgresql://localhost:5433/pot
      username: postgres
      password: postgres
      max-pool-size: 20

  config:
    consul:
      agent: http://consul:8500
  discovery:
    cluster: 1
    consul:
      agent: http://consul:8500
    ttl: 20
    ping-interval: 15

  health:
    checks:
      data-source-health-check:
        jndi-name: jdbc/potDS
        type: liveness
      http-health-check:
        - connection-url: http://localhost:8081/v1/pot


  metrics:
    web-instrumentation:
      - name: pot-endpoint
        url-pattern: /v1/pot/*
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                          <Configuration name="comments">
                              <Appenders>
                                  <Console name="console" target="SYSTEM_OUT">
                                      <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                  </Console>
                                  <Socket name="logstash" host="24c805d1-45a9-4d59-93b4-fc92236277b8-ls.logit.io"
                                  port="54321" protocol="udp">
                                      <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                                  </Socket>
                              </Appenders>
                              <Loggers>
                                  <!-- Default logger -->
                                  <Root level="all">
                                      <AppenderRef ref="console" level="info" />
                                      <AppenderRef ref="logstash" level="trace" />
                                  </Root>
                              </Loggers>
                          </Configuration>'

  external-api:
    mapquestApi: https://www.mapquestapi.com/directions/v2/optimizedroute?key=C0a6ATPbuQ30XjwFnoy7xAYYmajidgtD